function browseCtrl($scope, $http) {
    $scope.loans = [
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}},
        {"name":"Joyce","description":{"languages":["en"],"texts":{"en":"Joyce is a married businesslady who lives in Kilifi and sells roofing materials commonly referred to as ‘makuti.’ They are made from coconut leaves. These items are preferred for roofing in Kilifi area and at the coast in general, since they insulate from the heat experienced at the coast during the day time. \r\n\r\nJoyce has been running her business for seventeen years. She is married and has seven children.\r\n\r\nJoyce was introduced to Milango by her friends and is applying for a loan of 21,100 Kenyan shillings to purchase more coconut leaves and threads. Her main challenges are high inflation, which has reduced the purchasing power of most customers, and a lack of reliable customers, as well as the fluctuating demand for roofing materials. Joyce will save the additional income from this loan and use it to provide for her family.  \r\n"}},"funded_amount":250,"loan_amount":250,"image":{"id":1239510,"template_id":1},"activity":"Construction Supplies","use":"to purchase more coconut leaves and threads. ", "location": {"country_code": "KE","country": "Kenya", "town": null}}
    ];

    // Angular's ng-repeat does not get along with Carousel -- this hack is ugly but time is short :)
    function makeCarouselElement(loan) {
        return "<div class=\"carousel-element\" style=\"padding-top: 10px; background-image: url('http:\/\/www.kiva.org\/img\/w325\/" + loan.image.id + ".jpg');\"><div class=\"sm-preview\"><h3 class=\"sm-preview-head\">" + loan.name + " in " + loan.location.country + "</h3><p class='sm-preview-text'>needs help " + loan.use + "</p></div></div>";
    }

    var carouselHtmlString = "";

    angular.forEach($scope.loans, function (loan, idx) {
        carouselHtmlString += makeCarouselElement(loan);
    });

    $('#recommendations').append(carouselHtmlString);

    $("#recommendations").owlCarousel({
        pagination: true,
        autoPlay: 7000,
        // navigation: true,
        items: 3,
        itemsScaleUp: false
        // rewindSpeed: 0
    });

}